version: "3.8"

x-airflow-common: &airflow-common
  image: apache/airflow:2.5.1
  environment:
    AIRFLOW__CORE__EXECUTOR: SequentialExecutor   # sqlite
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "true"
    _PIP_ADDITIONAL_REQUIREMENTS: "-r /opt/airflow/dags/requirements.txt"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - airflow_home:/opt/airflow          # <-- share AIRFLOW_HOME (holds airflow.db)
  user: "${AIRFLOW_UID:-50000}:0"
  restart: always

services:
  airflow-init:
    <<: *airflow-common
    restart: "no"
    entrypoint: []
    command:
      - bash
      - -lc
      - |
          set -e
          python -m pip install --no-cache-dir -r /opt/airflow/dags/requirements.txt
          airflow db init
          airflow users create \
            --username ${_AIRFLOW_WWW_USER_USERNAME:-airflow2} \
            --firstname Admin --lastname User \
            --role Admin --email admin@example.com \
            --password ${_AIRFLOW_WWW_USER_PASSWORD:-airflow2}

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8081:8080"       # you’re using 8081 on the host
    depends_on:
      - airflow-init

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - airflow-init

volumes:
  airflow_home:
